SET XACT_ABORT ON;
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Players' AND COLUMN_NAME = 'VipExpireDate')
BEGIN
	BEGIN TRAN;
		ALTER TABLE dbo.Players DROP COLUMN IsVIP;
		ALTER TABLE dbo.Players DROP COLUMN VipExpireDate;
		ALTER TABLE dbo.Players ADD IsVIP BIT NOT NULL CONSTRAINT DF_Players_IsVIP DEFAULT 0 WITH VALUES;
	COMMIT;
END;